name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry and dependencies
      uses: snok/install-poetry@v1
    - name: Check formatting with black
      run: python -m black --check 
    - name: Check typehints with mypy
      run: python -m mypy
    - name: Run tests with pytest
      run: python -m pytest
